//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockFactoryApp.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlockFactoryApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;!doctype html&gt;
        ///&lt;html lang=&quot;ja-jp&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge,chrome=1&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///    &lt;title&gt;Blockly Demo: Blockly Developer Tools&lt;/title&gt;
        ///    &lt;style&gt;
        ////**
        /// * @license
        /// * Blockly Demos: Block Factory
        /// *
        /// * Copyright 2016 Google Inc.
        /// * https://developers.google.com/blockly/
        /// *
        /// * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
        /// * you may not use thi [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Canvas {
            get {
                return ResourceManager.GetString("Canvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;xml id=&quot;toolbox&quot; style=&quot;display: none&quot;&gt;
        ///  &lt;category name=&quot;Logic&quot; colour=&quot;210&quot;&gt;
        ///    &lt;block type=&quot;controls_if&quot;&gt;&lt;/block&gt;
        ///    &lt;block type=&quot;switch_case_number&quot;&gt;&lt;/block&gt;
        ///    &lt;block type=&quot;switch_case_text&quot;&gt;&lt;/block&gt;
        ///    &lt;block type=&quot;logic_compare&quot;&gt;&lt;/block&gt;
        ///    &lt;block type=&quot;logic_operation&quot;&gt;&lt;/block&gt;
        ///    &lt;block type=&quot;logic_negate&quot;&gt;&lt;/block&gt;
        ///    &lt;block type=&quot;logic_boolean&quot;&gt;&lt;/block&gt;
        ///    &lt;block type=&quot;logic_null&quot;&gt;&lt;/block&gt;
        ///    &lt;block type=&quot;logic_ternary&quot;&gt;&lt;/block&gt;
        ///  &lt;/cat [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbox {
            get {
                return ResourceManager.GetString("Toolbox", resourceCulture);
            }
        }
    }
}
